[app]
primary ansible_host=3.64.75.47 ansible_user=ubuntu instance_name=uty-api private_ip=10.0.1.48
secondary ansible_host=18.195.127.94 ansible_user=ubuntu instance_name=uty-api-secondary private_ip=10.0.2.164
